#!/bin/sh

set -e

root_dir=$(git rev-parse --show-toplevel)

. "$root_dir/scripts/venv.sh"
set_venv_python "$root_dir"

"$VENV_PY" -m pip install -r "$root_dir/requirements.txt"
sh "$root_dir/scripts/install.sh"
