#!/bin/sh

set -e

echo "🚀 Running pre-push hook 🚀"

echo -e "\n✨ Running unit tests..."

# pytest ./tests

echo -e "\n🔧 Installing/updating app on this computer..."

./scripts/install.sh

echo -e "\n🎉 Pre-push status: success 🎉\n"
